import type { ImagePreset } from '@/composables/stages/imagePresets'

const cat = 'videoChange' as const

export const VIDEO_CHANGE_PRESETS: ImagePreset[] = [
  { id: 'clip',            icon: 'lucide:scissors',  category: cat, targetClass: 'ComfyTV.VideoClipStage',                inputSocket: 'video' },
  { id: 'split',           icon: 'pi pi-pause',      category: cat, targetClass: 'ComfyTV.VideoSplitStage',               inputSocket: 'video' },
  { id: 'speed',           icon: 'pi pi-forward',    category: cat, targetClass: 'ComfyTV.VideoSpeedStage',               inputSocket: 'video' },
  { id: 'rotate',          icon: 'pi pi-refresh',    category: cat, targetClass: 'ComfyTV.VideoRotateStage',              inputSocket: 'video' },
  { id: 'crop',            icon: 'lucide:crop',      category: cat, targetClass: 'ComfyTV.VideoCropStage',                inputSocket: 'video' },
  { id: 'resize',          icon: 'pi pi-arrows-h',   category: cat, targetClass: 'ComfyTV.VideoResizeStage',              inputSocket: 'video' },
  { id: 'volume',          icon: 'pi pi-volume-up',  category: cat, targetClass: 'ComfyTV.VideoVolumeStage',              inputSocket: 'video' },
  { id: 'mux-audio',       icon: 'pi pi-headphones', category: cat, targetClass: 'ComfyTV.VideoMuxAudioStage',            inputSocket: 'video' },
  { id: 'concat',          icon: 'pi pi-link',       category: cat, targetClass: 'ComfyTV.VideoConcatStage',              inputAutogrowGroup: 'videos' },
  { id: 'extract-frame',   icon: 'pi pi-image',      category: cat, targetClass: 'ComfyTV.VideoExtractFrameStage',       inputSocket: 'video' },
  { id: 'frames',          icon: 'pi pi-images',     category: cat, targetClass: 'ComfyTV.VideoFramesStage',              inputSocket: 'video' },
  {
    id: 'demux',
    icon: 'pi pi-share-alt',
    category: cat,
    multiTargetClasses: [
      'ComfyTV.AudioVideoDemuxAudioStage',
      'ComfyTV.AudioVideoDemuxVideoStage',
    ],
    inputSocket: 'video',
  },
  { id: 'color',           icon: 'pi pi-palette',    category: cat, targetClass: 'ComfyTV.VideoColorStage',               inputSocket: 'video' },
  { id: 'curves',          icon: 'pi pi-chart-line', category: cat, targetClass: 'ComfyTV.VideoCurvesStage',              inputSocket: 'video' },
  { id: 'lut',             icon: 'pi pi-sliders-h',  category: cat, targetClass: 'ComfyTV.VideoLUTStage',                 inputSocket: 'video' },
  { id: 'blur-sharpen',    icon: 'pi pi-circle',     category: cat, targetClass: 'ComfyTV.VideoBlurSharpenStage',         inputSocket: 'video' },
  { id: 'denoise',         icon: 'pi pi-eraser',     category: cat, targetClass: 'ComfyTV.VideoDenoiseStage',             inputSocket: 'video' },
  { id: 'chroma-key',      icon: 'pi pi-filter',     category: cat, targetClass: 'ComfyTV.VideoChromaKeyStage',           inputSocket: 'video' },
  { id: 'transition',      icon: 'pi pi-arrow-right-arrow-left', category: cat, targetClass: 'ComfyTV.VideoTransitionStage', inputSocket: 'video_a' },
  { id: 'stabilize',       icon: 'pi pi-wave-pulse', category: cat, targetClass: 'ComfyTV.VideoStabilizeStage',           inputSocket: 'video' },
  { id: 'scene-detect',    icon: 'pi pi-th-large',   category: cat, targetClass: 'ComfyTV.SceneDetectStage',              inputSocket: 'video' },
  { id: 'interpolate',     icon: 'pi pi-fast-forward', category: cat, targetClass: 'ComfyTV.VideoInterpolateStage',       inputSocket: 'video' },
  { id: 'stylize',         icon: 'pi pi-sparkles',   category: cat, targetClass: 'ComfyTV.VideoStylizeStage',             inputSocket: 'video' },
  { id: 'scopes',          icon: 'pi pi-chart-bar',  category: cat, targetClass: 'ComfyTV.VideoScopesStage',              inputSocket: 'video' },
  { id: 'transform',       icon: 'pi pi-arrows-alt', category: cat, targetClass: 'ComfyTV.VideoTransformStage',           inputSocket: 'video' },
  { id: 'composite',       icon: 'pi pi-clone',      category: cat, targetClass: 'ComfyTV.VideoCompositeStage',           inputSocket: 'background' },
  { id: 'corner-pin',      icon: 'pi pi-expand',     category: cat, targetClass: 'ComfyTV.CornerPinStage',                inputSocket: 'video' },
  { id: 'roto-mask',       icon: 'pi pi-pencil',     category: cat, targetClass: 'ComfyTV.RotoMaskStage',                 inputSocket: 'video' },
  { id: 'motion-track',    icon: 'pi pi-map-marker', category: cat, targetClass: 'ComfyTV.MotionTrackStage',              inputSocket: 'video' },
  { id: 'title',           icon: 'pi pi-align-center', category: cat, targetClass: 'ComfyTV.TitleStage',                  inputSocket: 'video' },
  { id: 'subtitles',       icon: 'pi pi-comment',    category: cat, targetClass: 'ComfyTV.SubtitleStage',                 inputSocket: 'video' },
  { id: 'time-remap',      icon: 'pi pi-history',    category: cat, targetClass: 'ComfyTV.TimeRemapStage',                inputSocket: 'video' },
  { id: 'sequence',        icon: 'pi pi-list',       category: cat, targetClass: 'ComfyTV.SequenceStage',                 inputAutogrowGroup: 'videos' },
  { id: 'stabilize-pro',   icon: 'pi pi-shield',     category: cat, targetClass: 'ComfyTV.VideoStabilizeV2Stage',         inputSocket: 'video' },
  { id: 'paint',           icon: 'pi pi-pencil',     category: cat, targetClass: 'ComfyTV.PaintStrokeStage',              inputSocket: 'video' },
  { id: 'uv-remap',        icon: 'pi pi-table',      category: cat, targetClass: 'ComfyTV.STMapStage',                    inputSocket: 'video' },
  { id: 'mask-propagate',  icon: 'pi pi-forward',    category: cat, targetClass: 'ComfyTV.MaskPropagateStage',            inputSocket: 'video' },
  { id: 'speech-to-text',  icon: 'pi pi-microphone', category: cat, targetClass: 'ComfyTV.SubtitleGenStage',              inputSocket: 'video' },
  { id: 'hue-correct',     icon: 'pi pi-sliders-v',  category: cat, targetClass: 'ComfyTV.HueCorrectStage',               inputSocket: 'video' },
  { id: 'glow',            icon: 'pi pi-sun',        category: cat, targetClass: 'ComfyTV.GlowStage',                     inputSocket: 'video' },
  { id: 'god-rays',        icon: 'pi pi-bolt',       category: cat, targetClass: 'ComfyTV.GodRaysStage',                  inputSocket: 'video' },
  { id: 'pik-keyer',       icon: 'pi pi-eraser',     category: cat, targetClass: 'ComfyTV.PIKStage',                      inputSocket: 'video' },
  { id: 'keyer',           icon: 'pi pi-filter',     category: cat, targetClass: 'ComfyTV.KeyerStage',                    inputSocket: 'video' },
  { id: 'despill',         icon: 'pi pi-eraser',     category: cat, targetClass: 'ComfyTV.DespillStage',                  inputSocket: 'video' },
  { id: 'color-suppress',  icon: 'pi pi-filter-slash', category: cat, targetClass: 'ComfyTV.ColorSuppressStage',          inputSocket: 'video' },
  { id: 'key-mix',         icon: 'pi pi-clone',      category: cat, targetClass: 'ComfyTV.KeyMixStage',                   inputSocket: 'video_a' },
  { id: 'matte-monitor',   icon: 'pi pi-eye',        category: cat, targetClass: 'ComfyTV.MatteMonitorStage',             inputSocket: 'video' },
  { id: 'matte-morph',     icon: 'pi pi-circle',     category: cat, targetClass: 'ComfyTV.MatteMorphStage',               inputSocket: 'video' },
  { id: 'frame-blend',     icon: 'pi pi-images',     category: cat, targetClass: 'ComfyTV.FrameBlendStage',               inputSocket: 'video' },
  { id: 'color-fx',        icon: 'pi pi-palette',    category: cat, targetClass: 'ComfyTV.ColorFXStage',                  inputSocket: 'video' },
  { id: 'old-film',        icon: 'pi pi-video',      category: cat, targetClass: 'ComfyTV.OldFilmStage',                  inputSocket: 'video' },
  { id: 'annotate',        icon: 'pi pi-pencil',     category: cat, targetClass: 'ComfyTV.AnnotateStage',                 inputSocket: 'video' },
  { id: 'audio-reactive',  icon: 'pi pi-wave-pulse', category: cat, targetClass: 'ComfyTV.AudioReactiveStage',            inputSocket: 'video' },
  { id: 'audio-meter',     icon: 'pi pi-chart-bar',  category: cat, targetClass: 'ComfyTV.AudioMeterStage',               inputSocket: 'video' },
  { id: 'fx-chain',        icon: 'pi pi-sitemap',    category: cat, targetClass: 'ComfyTV.FXChainStage',                  inputSocket: 'video' },
]
