STAGE_META: dict[str, dict] = {
    'ProjectStage':                 {'kind': 'project'},
    'TextStage':                    {'kind': 'text',         'workflow_kind': 'text'},
    'ImageStage':                   {'kind': 'image-batch',  'workflow_kind': 'image'},
    'VideoStage':                   {'kind': 'video',        'workflow_kind': 'video'},
    'AudioStage':                   {'kind': 'audio',        'workflow_kind': 'audio'},
    'SpeechStage':                  {'kind': 'audio',        'workflow_kind': 'speech'},
    'ImagePickerStage':             {'kind': 'image-picker'},
    'AudioPickerStage':             {'kind': 'audio-picker'},
    'VideoPickerStage':             {'kind': 'video-picker'},
    'ShotImagesStage':              {'kind': 'image-batch',  'workflow_kind': 'shot-images'},
    'UpscaleStage':                 {'kind': 'image',        'workflow_kind': 'upscale'},
    'OutpaintStage':                {'kind': 'image',        'workflow_kind': 'outpaint'},
    'InpaintStage':                 {'kind': 'image',        'workflow_kind': 'inpaint'},
    'ImageEditStage':               {'kind': 'image',        'workflow_kind': 'image-edit'},
    'BridgeToText':                 {'kind': 'text'},
    'BridgeToImage':                {'kind': 'image'},
    'BridgeToImages':               {'kind': 'image-batch'},
    'BridgeToVideo':                {'kind': 'video'},
    'BridgeToAudio':                {'kind': 'audio'},
    'EraseStage':                   {'kind': 'image',        'workflow_kind': 'erase'},
    'CutoutStage':                  {'kind': 'image',        'workflow_kind': 'cutout'},
    'SplitPartStage':               {'kind': 'image-batch',  'workflow_kind': 'split-part'},
    'CropStage':                    {'kind': 'image',       'variant': 'transform'},
    'RotateStage':                  {'kind': 'image',       'variant': 'transform'},
    'MirrorStage':                  {'kind': 'image',       'variant': 'transform'},
    'ColorGradeStage':              {'kind': 'image',       'variant': 'transform'},
    'CompareStage':                 {'kind': 'image',       'variant': 'transform'},
    'GridSplitStage':               {'kind': 'image-batch', 'variant': 'transform'},
    'DirectorTimelineStage':        {'kind': 'timeline',    'variant': 'transform'},
    'TimelineVideoStage':           {'kind': 'video',        'workflow_kind': 'timeline'},
    'ImageVariationsStage':         {'kind': 'image-batch',  'workflow_kind': 'multiview'},
    'RelightStage':                 {'kind': 'image',       'variant': 'loader'},
    'MultiangleStage':              {'kind': 'image',        'workflow_kind': 'multiangle'},
    'VideoExtractFrameStage':       {'kind': 'image'},
    'VideoClipStage':               {'kind': 'video'},
    'VideoCropStage':               {'kind': 'video'},
    'VideoConcatStage':             {'kind': 'video'},
    'VideoSpeedStage':              {'kind': 'video'},
    'VideoRotateStage':             {'kind': 'video'},
    'VideoSplitStage':              {'kind': 'video'},
    'VideoVolumeStage':             {'kind': 'video'},
    'VideoMuxAudioStage':           {'kind': 'video'},
    'VideoFramesStage':             {'kind': 'image-batch'},
    'VideoResizeStage':             {'kind': 'video'},
    'VideoUpscaleStage':            {'kind': 'video',        'workflow_kind': 'upscale'},
    'VideoSubtitleSmartEraseStage': {'kind': 'video'},
    'VideoSubtitleSelectEraseStage':{'kind': 'video'},
    'AudioExtractVocalStage':       {'kind': 'audio',        'workflow_kind': 'audio-vocal'},
    'AudioExtractBgStage':          {'kind': 'audio',        'workflow_kind': 'audio-bg'},
    'AudioVideoDemuxAudioStage':    {'kind': 'audio'},
    'AudioVideoDemuxVideoStage':    {'kind': 'video'},
    'VideoColorStage':              {'kind': 'video'},
    'VideoCurvesStage':             {'kind': 'video'},
    'VideoLUTStage':                {'kind': 'video'},
    'VideoBlurSharpenStage':        {'kind': 'video'},
    'VideoDenoiseStage':            {'kind': 'video'},
    'VideoChromaKeyStage':          {'kind': 'video'},
    'VideoTransitionStage':         {'kind': 'video'},
    'VideoStabilizeStage':          {'kind': 'video'},
    'SceneDetectStage':             {'kind': 'image-batch'},
    'VideoInterpolateStage':        {'kind': 'video'},
    'VideoDeinterlaceStage':        {'kind': 'video'},
    'VideoStylizeStage':            {'kind': 'video'},
    'VideoScopesStage':             {'kind': 'image'},
    'AudioDynamicsStage':           {'kind': 'audio'},
    'AudioEQStage':                 {'kind': 'audio'},
    'AudioLoudnessStage':           {'kind': 'audio'},
    'AudioDenoiseStage':            {'kind': 'audio'},
    'AudioEchoStage':               {'kind': 'audio'},
    'AudioModulationStage':         {'kind': 'audio'},
    'AudioStereoStage':             {'kind': 'audio'},
    'AudioTimePitchStage':          {'kind': 'audio'},
    'AudioRepairStage':             {'kind': 'audio'},
    'AudioSaturateStage':           {'kind': 'audio'},
    'AudioCrossfadeStage':          {'kind': 'audio'},
    'AudioAnalyzeStage':            {'kind': 'text'},
    'AudioVisualizeStage':          {'kind': 'image'},
    'VideoCompositeStage':          {'kind': 'video'},
    'VideoTransformStage':          {'kind': 'video'},
    'CornerPinStage':               {'kind': 'video'},
    'RotoMaskStage':                {'kind': 'video'},
    'MotionTrackStage':             {'kind': 'text'},
    'TitleStage':                   {'kind': 'video'},
    'SubtitleStage':                {'kind': 'video'},
    'TimeRemapStage':               {'kind': 'video'},
    'SequenceStage':                {'kind': 'video'},
    'VideoStabilizeV2Stage':        {'kind': 'video'},
    'PaintStrokeStage':             {'kind': 'video'},
    'STMapStage':                   {'kind': 'video'},
    'MaskPropagateStage':           {'kind': 'video'},
    'SubtitleGenStage':             {'kind': 'text', 'workflow_kind': 'speech-to-text'},
    'HueCorrectStage':              {'kind': 'video'},
    'GlowStage':                    {'kind': 'video'},
    'GodRaysStage':                 {'kind': 'video'},
    'PatternStage':                 {'kind': 'video'},
    'PanoramaStage':                {'kind': 'panorama',     'workflow_kind': 'panorama'},
    'PanoramaCurrentViewStage':     {'kind': 'image',       'variant': 'transform'},
    'PanoramaMultiViewStage':       {'kind': 'image-batch', 'variant': 'transform'},
    'StoryboardStage':              {'kind': 'storyboard',   'workflow_kind': 'storyboard'},
    'ImageLoaderStage':             {'kind': 'image',       'variant': 'loader'},
    'VideoLoaderStage':             {'kind': 'video',       'variant': 'loader'},
    'AudioLoaderStage':             {'kind': 'audio',       'variant': 'loader'},
    'AssetImageLoaderStage':        {'kind': 'image',       'variant': 'loader'},
    'AssetVideoLoaderStage':        {'kind': 'video',       'variant': 'loader'},
    'AssetAudioLoaderStage':        {'kind': 'audio',       'variant': 'loader'},
    'Scene3DStage':                 {'kind': 'image',       'variant': 'loader'},
    'LayerEditorStage':             {'kind': 'image',       'variant': 'loader'},
    'MaterialStage':                {'kind': 'material',     'workflow_kind': 'material-estimate'},
    'Model3DStage':                 {'kind': 'model',        'workflow_kind': 'model'},
    'ModelLoaderStage':             {'kind': 'model',       'variant': 'loader'},
    'AssetModelLoaderStage':        {'kind': 'model',       'variant': 'loader'},
    'MeshOpStage':                  {'kind': 'model'},
    'MeshBakeMapsStage':            {'kind': 'model'},
    'MeshPrimitiveStage':           {'kind': 'model'},
    'MeshBooleanStage':             {'kind': 'model'},
}


_KIND_TO_OUTPUT_TYPE: dict[str, str] = {
    'image-batch':  'images',
    'image-picker': 'image',
    'audio-picker': 'audio',
    'video-picker': 'video',
}
