STAGE_META: dict[str, dict] = {
    'ProjectStage':                 {'kind': 'project'},
    'TextStage':                    {'kind': 'text',         'workflow_kind': 'text'},
    'ImageStage':                   {'kind': 'image-batch',  'workflow_kind': 'image'},
    'VideoStage':                   {'kind': 'video',        'workflow_kind': 'video'},
    'AudioStage':                   {'kind': 'audio',        'workflow_kind': 'audio'},
    'SpeechStage':                  {'kind': 'audio',        'workflow_kind': 'speech'},
    'ImagePickerStage':             {'kind': 'image-picker'},
    'AudioPickerStage':             {'kind': 'audio-picker'},
    'VideoPickerStage':             {'kind': 'video-picker'},
    'ShotImagesStage':              {'kind': 'image-batch',  'workflow_kind': 'shot-images'},
    'UpscaleStage':                 {'kind': 'image',        'workflow_kind': 'upscale'},
    'OutpaintStage':                {'kind': 'image',        'workflow_kind': 'outpaint'},
    'InpaintStage':                 {'kind': 'image',        'workflow_kind': 'inpaint'},
    'ImageEditStage':               {'kind': 'image',        'workflow_kind': 'image-edit'},
    'BridgeToText':                 {'kind': 'text'},
    'BridgeToImage':                {'kind': 'image'},
    'BridgeToImages':               {'kind': 'image-batch'},
    'BridgeToVideo':                {'kind': 'video'},
    'BridgeToAudio':                {'kind': 'audio'},
    'EraseStage':                   {'kind': 'image',        'workflow_kind': 'erase'},
    'CutoutStage':                  {'kind': 'image',        'workflow_kind': 'cutout'},
    'CropStage':                    {'kind': 'image',       'variant': 'transform'},
    'RotateStage':                  {'kind': 'image',       'variant': 'transform'},
    'MirrorStage':                  {'kind': 'image',       'variant': 'transform'},
    'ColorGradeStage':              {'kind': 'image',       'variant': 'transform'},
    'CompareStage':                 {'kind': 'image',       'variant': 'transform'},
    'GridSplitStage':               {'kind': 'image-batch', 'variant': 'transform'},
    'DirectorTimelineStage':        {'kind': 'timeline',    'variant': 'transform'},
    'TimelineVideoStage':           {'kind': 'video',        'workflow_kind': 'timeline'},
    'ImageVariationsStage':         {'kind': 'image-batch',  'workflow_kind': 'multiview'},
    'RelightStage':                 {'kind': 'image',       'variant': 'loader'},
    'MultiangleStage':              {'kind': 'image',        'workflow_kind': 'multiangle'},
    'VideoExtractFrameStage':       {'kind': 'image'},
    'VideoClipStage':               {'kind': 'video'},
    'VideoCropStage':               {'kind': 'video'},
    'VideoResizeStage':             {'kind': 'video'},
    'VideoUpscaleStage':            {'kind': 'video',        'workflow_kind': 'upscale'},
    'VideoSubtitleSmartEraseStage': {'kind': 'video'},
    'VideoSubtitleSelectEraseStage':{'kind': 'video'},
    'AudioExtractVocalStage':       {'kind': 'audio',        'workflow_kind': 'audio-vocal'},
    'AudioExtractBgStage':          {'kind': 'audio',        'workflow_kind': 'audio-bg'},
    'AudioVideoDemuxAudioStage':    {'kind': 'audio'},
    'AudioVideoDemuxVideoStage':    {'kind': 'video'},
    'PanoramaStage':                {'kind': 'panorama',     'workflow_kind': 'panorama'},
    'PanoramaCurrentViewStage':     {'kind': 'image',       'variant': 'transform'},
    'PanoramaMultiViewStage':       {'kind': 'image-batch', 'variant': 'transform'},
    'StoryboardStage':              {'kind': 'storyboard',   'workflow_kind': 'storyboard'},
    'ImageLoaderStage':             {'kind': 'image',       'variant': 'loader'},
    'VideoLoaderStage':             {'kind': 'video',       'variant': 'loader'},
    'AudioLoaderStage':             {'kind': 'audio',       'variant': 'loader'},
    'AssetImageLoaderStage':        {'kind': 'image',       'variant': 'loader'},
    'AssetVideoLoaderStage':        {'kind': 'video',       'variant': 'loader'},
    'AssetAudioLoaderStage':        {'kind': 'audio',       'variant': 'loader'},
    'Scene3DStage':                 {'kind': 'image',       'variant': 'loader'},
    'Model3DStage':                 {'kind': 'model',        'workflow_kind': 'model'},
    'ModelLoaderStage':             {'kind': 'model',       'variant': 'loader'},
    'AssetModelLoaderStage':        {'kind': 'model',       'variant': 'loader'},
}


_KIND_TO_OUTPUT_TYPE: dict[str, str] = {
    'image-batch':  'images',
    'image-picker': 'image',
    'audio-picker': 'audio',
    'video-picker': 'video',
}
