from comfy_api.latest import io


COMFYTV_SCHEMA_VERSION = 1

COMFYTV_TEXT       = io.Custom("COMFYTV_TEXT")
COMFYTV_IMAGE      = io.Custom("COMFYTV_IMAGE")
COMFYTV_VIDEO      = io.Custom("COMFYTV_VIDEO")
COMFYTV_STORYBOARD = io.Custom("COMFYTV_STORYBOARD")
COMFYTV_IMAGES     = io.Custom("COMFYTV_IMAGES")
COMFYTV_PANORAMA   = io.Custom("COMFYTV_PANORAMA")
COMFYTV_AUDIO      = io.Custom("COMFYTV_AUDIO")
COMFYTV_TIMELINE   = io.Custom("COMFYTV_TIMELINE")
COMFYTV_MODEL      = io.Custom("COMFYTV_MODEL")
COMFYTV_MATERIAL   = io.Custom("COMFYTV_MATERIAL")
